slam_manager:
  ros__parameters:
    mode: external_odom
    external_stack_profile: external_odom
    mapping_stack_profile: slam_toolbox
    primary_map_representation: occupancy_grid_2d
    localization_representation: occupancy_grid_2d
    navigation_representation: occupancy_grid_2d
    web_map_representation: occupancy_grid_2d
    front_lidar_input_topic: /jt128/front/points
    front_lidar_input_type: sensor_msgs/msg/PointCloud2
    pointcloud_projection_enabled: false
    pointcloud_topic: /jt128/front/points
    imu_topic: /jt128/front/imu
    odom_topic: /odom
    odom_topic_candidates: [/odom]
    map_frame: map
    odom_frame: odom
    base_frame: base_link
    project_to_nav2_map: false
