# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from common import alarm_pb2 as common_dot_alarm__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in common/alarm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AlarmServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAlarms = channel.unary_unary(
                '/physical.common.AlarmService/GetAlarms',
                request_serializer=common_dot_alarm__pb2.GetAlarmsRequest.SerializeToString,
                response_deserializer=common_dot_alarm__pb2.GetAlarmsResponse.FromString,
                _registered_method=True)
        self.AcknowledgeAlarm = channel.unary_unary(
                '/physical.common.AlarmService/AcknowledgeAlarm',
                request_serializer=common_dot_alarm__pb2.AcknowledgeAlarmRequest.SerializeToString,
                response_deserializer=common_dot_alarm__pb2.Alarm.FromString,
                _registered_method=True)
        self.ClearAlarm = channel.unary_unary(
                '/physical.common.AlarmService/ClearAlarm',
                request_serializer=common_dot_alarm__pb2.ClearAlarmRequest.SerializeToString,
                response_deserializer=common_dot_alarm__pb2.Alarm.FromString,
                _registered_method=True)
        self.WatchAlarms = channel.unary_stream(
                '/physical.common.AlarmService/WatchAlarms',
                request_serializer=common_dot_alarm__pb2.WatchAlarmsRequest.SerializeToString,
                response_deserializer=common_dot_alarm__pb2.Alarm.FromString,
                _registered_method=True)
        self.GetAlarmStatistics = channel.unary_unary(
                '/physical.common.AlarmService/GetAlarmStatistics',
                request_serializer=common_dot_alarm__pb2.GetAlarmStatisticsRequest.SerializeToString,
                response_deserializer=common_dot_alarm__pb2.GetAlarmStatisticsResponse.FromString,
                _registered_method=True)


class AlarmServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAlarms(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcknowledgeAlarm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearAlarm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchAlarms(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAlarmStatistics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AlarmServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAlarms': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAlarms,
                    request_deserializer=common_dot_alarm__pb2.GetAlarmsRequest.FromString,
                    response_serializer=common_dot_alarm__pb2.GetAlarmsResponse.SerializeToString,
            ),
            'AcknowledgeAlarm': grpc.unary_unary_rpc_method_handler(
                    servicer.AcknowledgeAlarm,
                    request_deserializer=common_dot_alarm__pb2.AcknowledgeAlarmRequest.FromString,
                    response_serializer=common_dot_alarm__pb2.Alarm.SerializeToString,
            ),
            'ClearAlarm': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearAlarm,
                    request_deserializer=common_dot_alarm__pb2.ClearAlarmRequest.FromString,
                    response_serializer=common_dot_alarm__pb2.Alarm.SerializeToString,
            ),
            'WatchAlarms': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchAlarms,
                    request_deserializer=common_dot_alarm__pb2.WatchAlarmsRequest.FromString,
                    response_serializer=common_dot_alarm__pb2.Alarm.SerializeToString,
            ),
            'GetAlarmStatistics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAlarmStatistics,
                    request_deserializer=common_dot_alarm__pb2.GetAlarmStatisticsRequest.FromString,
                    response_serializer=common_dot_alarm__pb2.GetAlarmStatisticsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'physical.common.AlarmService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('physical.common.AlarmService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AlarmService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAlarms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.common.AlarmService/GetAlarms',
            common_dot_alarm__pb2.GetAlarmsRequest.SerializeToString,
            common_dot_alarm__pb2.GetAlarmsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcknowledgeAlarm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.common.AlarmService/AcknowledgeAlarm',
            common_dot_alarm__pb2.AcknowledgeAlarmRequest.SerializeToString,
            common_dot_alarm__pb2.Alarm.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearAlarm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.common.AlarmService/ClearAlarm',
            common_dot_alarm__pb2.ClearAlarmRequest.SerializeToString,
            common_dot_alarm__pb2.Alarm.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchAlarms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/physical.common.AlarmService/WatchAlarms',
            common_dot_alarm__pb2.WatchAlarmsRequest.SerializeToString,
            common_dot_alarm__pb2.Alarm.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAlarmStatistics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.common.AlarmService/GetAlarmStatistics',
            common_dot_alarm__pb2.GetAlarmStatisticsRequest.SerializeToString,
            common_dot_alarm__pb2.GetAlarmStatisticsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
