# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from common import audio_pb2 as common_dot_audio__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in common/audio_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SpeakerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PlayAudio = channel.unary_unary(
                '/physical.common.SpeakerService/PlayAudio',
                request_serializer=common_dot_audio__pb2.PlayAudioRequest.SerializeToString,
                response_deserializer=common_dot_audio__pb2.PlayAudioResponse.FromString,
                _registered_method=True)
        self.StopAudio = channel.unary_unary(
                '/physical.common.SpeakerService/StopAudio',
                request_serializer=common_dot_audio__pb2.StopAudioRequest.SerializeToString,
                response_deserializer=common_dot_audio__pb2.StopAudioResponse.FromString,
                _registered_method=True)
        self.GetSpeakerStatus = channel.unary_unary(
                '/physical.common.SpeakerService/GetSpeakerStatus',
                request_serializer=common_dot_audio__pb2.GetSpeakerStatusRequest.SerializeToString,
                response_deserializer=common_dot_audio__pb2.SpeakerStatus.FromString,
                _registered_method=True)


class SpeakerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PlayAudio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopAudio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSpeakerStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpeakerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PlayAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.PlayAudio,
                    request_deserializer=common_dot_audio__pb2.PlayAudioRequest.FromString,
                    response_serializer=common_dot_audio__pb2.PlayAudioResponse.SerializeToString,
            ),
            'StopAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.StopAudio,
                    request_deserializer=common_dot_audio__pb2.StopAudioRequest.FromString,
                    response_serializer=common_dot_audio__pb2.StopAudioResponse.SerializeToString,
            ),
            'GetSpeakerStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSpeakerStatus,
                    request_deserializer=common_dot_audio__pb2.GetSpeakerStatusRequest.FromString,
                    response_serializer=common_dot_audio__pb2.SpeakerStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'physical.common.SpeakerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('physical.common.SpeakerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SpeakerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PlayAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.common.SpeakerService/PlayAudio',
            common_dot_audio__pb2.PlayAudioRequest.SerializeToString,
            common_dot_audio__pb2.PlayAudioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.common.SpeakerService/StopAudio',
            common_dot_audio__pb2.StopAudioRequest.SerializeToString,
            common_dot_audio__pb2.StopAudioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSpeakerStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.common.SpeakerService/GetSpeakerStatus',
            common_dot_audio__pb2.GetSpeakerStatusRequest.SerializeToString,
            common_dot_audio__pb2.SpeakerStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MicrophoneServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CaptureAudio = channel.unary_unary(
                '/physical.common.MicrophoneService/CaptureAudio',
                request_serializer=common_dot_audio__pb2.CaptureAudioRequest.SerializeToString,
                response_deserializer=common_dot_audio__pb2.CaptureAudioResponse.FromString,
                _registered_method=True)
        self.GetMicrophoneStatus = channel.unary_unary(
                '/physical.common.MicrophoneService/GetMicrophoneStatus',
                request_serializer=common_dot_audio__pb2.GetMicrophoneStatusRequest.SerializeToString,
                response_deserializer=common_dot_audio__pb2.MicrophoneStatus.FromString,
                _registered_method=True)


class MicrophoneServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CaptureAudio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMicrophoneStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MicrophoneServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CaptureAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.CaptureAudio,
                    request_deserializer=common_dot_audio__pb2.CaptureAudioRequest.FromString,
                    response_serializer=common_dot_audio__pb2.CaptureAudioResponse.SerializeToString,
            ),
            'GetMicrophoneStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMicrophoneStatus,
                    request_deserializer=common_dot_audio__pb2.GetMicrophoneStatusRequest.FromString,
                    response_serializer=common_dot_audio__pb2.MicrophoneStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'physical.common.MicrophoneService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('physical.common.MicrophoneService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MicrophoneService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CaptureAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.common.MicrophoneService/CaptureAudio',
            common_dot_audio__pb2.CaptureAudioRequest.SerializeToString,
            common_dot_audio__pb2.CaptureAudioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMicrophoneStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.common.MicrophoneService/GetMicrophoneStatus',
            common_dot_audio__pb2.GetMicrophoneStatusRequest.SerializeToString,
            common_dot_audio__pb2.MicrophoneStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
