# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/light.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'common/light.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63ommon/light.proto\x12\x0fphysical.common\"-\n\nLightColor\x12\t\n\x01r\x18\x01 \x01(\r\x12\t\n\x01g\x18\x02 \x01(\r\x12\t\n\x01\x62\x18\x03 \x01(\r\"\xc4\x01\n\x0fSetLightRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\n\n\x02on\x18\x02 \x01(\x08\x12\x11\n\tintensity\x18\x03 \x01(\r\x12\x33\n\ncolor_mode\x18\x04 \x01(\x0e\x32\x1f.physical.common.LightColorMode\x12(\n\x03rgb\x18\x05 \x01(\x0b\x32\x1b.physical.common.LightColor\x12 \n\x18\x63olor_temperature_kelvin\x18\x06 \x01(\r\"b\n\x10SetLightResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12,\n\x06status\x18\x03 \x01(\x0b\x32\x1c.physical.common.LightStatus\"*\n\x15GetLightStatusRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\"\xd3\x01\n\x0bLightStatus\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\n\n\x02on\x18\x02 \x01(\x08\x12\x11\n\tintensity\x18\x03 \x01(\r\x12\x33\n\ncolor_mode\x18\x04 \x01(\x0e\x32\x1f.physical.common.LightColorMode\x12(\n\x03rgb\x18\x05 \x01(\x0b\x32\x1b.physical.common.LightColor\x12 \n\x18\x63olor_temperature_kelvin\x18\x06 \x01(\r\x12\x11\n\ttimestamp\x18\x07 \x01(\x03*\x82\x01\n\x0eLightColorMode\x12 \n\x1cLIGHT_COLOR_MODE_UNSPECIFIED\x10\x00\x12\x1a\n\x16LIGHT_COLOR_MODE_WHITE\x10\x01\x12\x18\n\x14LIGHT_COLOR_MODE_RGB\x10\x02\x12\x18\n\x14LIGHT_COLOR_MODE_CCT\x10\x03\x32\xb7\x01\n\x0cLightService\x12O\n\x08SetLight\x12 .physical.common.SetLightRequest\x1a!.physical.common.SetLightResponse\x12V\n\x0eGetLightStatus\x12&.physical.common.GetLightStatusRequest\x1a\x1c.physical.common.LightStatusB%Z#github.com/feishu/core/proto/commonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.light_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z#github.com/feishu/core/proto/common'
  _globals['_LIGHTCOLORMODE']._serialized_start=644
  _globals['_LIGHTCOLORMODE']._serialized_end=774
  _globals['_LIGHTCOLOR']._serialized_start=39
  _globals['_LIGHTCOLOR']._serialized_end=84
  _globals['_SETLIGHTREQUEST']._serialized_start=87
  _globals['_SETLIGHTREQUEST']._serialized_end=283
  _globals['_SETLIGHTRESPONSE']._serialized_start=285
  _globals['_SETLIGHTRESPONSE']._serialized_end=383
  _globals['_GETLIGHTSTATUSREQUEST']._serialized_start=385
  _globals['_GETLIGHTSTATUSREQUEST']._serialized_end=427
  _globals['_LIGHTSTATUS']._serialized_start=430
  _globals['_LIGHTSTATUS']._serialized_end=641
  _globals['_LIGHTSERVICE']._serialized_start=777
  _globals['_LIGHTSERVICE']._serialized_end=960
# @@protoc_insertion_point(module_scope)
