# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from common import light_pb2 as common_dot_light__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in common/light_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LightServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetLight = channel.unary_unary(
                '/physical.common.LightService/SetLight',
                request_serializer=common_dot_light__pb2.SetLightRequest.SerializeToString,
                response_deserializer=common_dot_light__pb2.SetLightResponse.FromString,
                _registered_method=True)
        self.GetLightStatus = channel.unary_unary(
                '/physical.common.LightService/GetLightStatus',
                request_serializer=common_dot_light__pb2.GetLightStatusRequest.SerializeToString,
                response_deserializer=common_dot_light__pb2.LightStatus.FromString,
                _registered_method=True)


class LightServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetLight(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLightStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LightServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetLight': grpc.unary_unary_rpc_method_handler(
                    servicer.SetLight,
                    request_deserializer=common_dot_light__pb2.SetLightRequest.FromString,
                    response_serializer=common_dot_light__pb2.SetLightResponse.SerializeToString,
            ),
            'GetLightStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLightStatus,
                    request_deserializer=common_dot_light__pb2.GetLightStatusRequest.FromString,
                    response_serializer=common_dot_light__pb2.LightStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'physical.common.LightService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('physical.common.LightService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LightService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetLight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.common.LightService/SetLight',
            common_dot_light__pb2.SetLightRequest.SerializeToString,
            common_dot_light__pb2.SetLightResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLightStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.common.LightService/GetLightStatus',
            common_dot_light__pb2.GetLightStatusRequest.SerializeToString,
            common_dot_light__pb2.LightStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
