# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/registry.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'common/registry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63ommon/registry.proto\x12\x0fphysical.common\"\x8d\x01\n\x0cUpstreamInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x0c\n\x04\x61\x64\x64r\x18\x04 \x01(\t\x12\x10\n\x08services\x18\x05 \x03(\t\x12\x30\n\x04meta\x18\x06 \x03(\x0b\x32\".physical.common.UpstreamMetaEntry\"e\n\x11UpstreamMetaEntry\x12-\n\x03key\x18\x01 \x01(\x0e\x32 .physical.common.UpstreamMetaKey\x12\r\n\x05value\x18\x02 \x01(\t\x12\x12\n\ncustom_key\x18\x03 \x01(\t\"J\n\x17RegistryRegisterRequest\x12/\n\x08upstream\x18\x01 \x01(\x0b\x32\x1d.physical.common.UpstreamInfo\"K\n\x18RegistryRegisterResponse\x12/\n\x08upstream\x18\x01 \x01(\x0b\x32\x1d.physical.common.UpstreamInfo\")\n\x19RegistryUnregisterRequest\x12\x0c\n\x04\x61\x64\x64r\x18\x01 \x01(\t\"(\n\x1aRegistryUnregisterResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\"1\n\x13RegistryListRequest\x12\x1a\n\x12include_proxy_info\x18\x01 \x01(\x08\"|\n\x14RegistryListResponse\x12\x30\n\tupstreams\x18\x01 \x03(\x0b\x32\x1d.physical.common.UpstreamInfo\x12\x19\n\x11proxy_grpc_listen\x18\x02 \x01(\t\x12\x17\n\x0fproxy_grpc_port\x18\x03 \x01(\x05*\xc2\x01\n\x0fUpstreamMetaKey\x12!\n\x1dUPSTREAM_META_KEY_UNSPECIFIED\x10\x00\x12\"\n\x1eUPSTREAM_META_KEY_DEVICE_MODEL\x10\x01\x12#\n\x1fUPSTREAM_META_KEY_DEVICE_VENDOR\x10\x02\x12$\n UPSTREAM_META_KEY_DEVICE_VERSION\x10\x03\x12\x1d\n\x18UPSTREAM_META_KEY_CUSTOM\x10\xe8\x07\x32\xae\x02\n\x0fRegistryService\x12_\n\x08Register\x12(.physical.common.RegistryRegisterRequest\x1a).physical.common.RegistryRegisterResponse\x12\x65\n\nUnregister\x12*.physical.common.RegistryUnregisterRequest\x1a+.physical.common.RegistryUnregisterResponse\x12S\n\x04List\x12$.physical.common.RegistryListRequest\x1a%.physical.common.RegistryListResponseB%Z#github.com/feishu/core/proto/commonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.registry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z#github.com/feishu/core/proto/common'
  _globals['_UPSTREAMMETAKEY']._serialized_start=705
  _globals['_UPSTREAMMETAKEY']._serialized_end=899
  _globals['_UPSTREAMINFO']._serialized_start=43
  _globals['_UPSTREAMINFO']._serialized_end=184
  _globals['_UPSTREAMMETAENTRY']._serialized_start=186
  _globals['_UPSTREAMMETAENTRY']._serialized_end=287
  _globals['_REGISTRYREGISTERREQUEST']._serialized_start=289
  _globals['_REGISTRYREGISTERREQUEST']._serialized_end=363
  _globals['_REGISTRYREGISTERRESPONSE']._serialized_start=365
  _globals['_REGISTRYREGISTERRESPONSE']._serialized_end=440
  _globals['_REGISTRYUNREGISTERREQUEST']._serialized_start=442
  _globals['_REGISTRYUNREGISTERREQUEST']._serialized_end=483
  _globals['_REGISTRYUNREGISTERRESPONSE']._serialized_start=485
  _globals['_REGISTRYUNREGISTERRESPONSE']._serialized_end=525
  _globals['_REGISTRYLISTREQUEST']._serialized_start=527
  _globals['_REGISTRYLISTREQUEST']._serialized_end=576
  _globals['_REGISTRYLISTRESPONSE']._serialized_start=578
  _globals['_REGISTRYLISTRESPONSE']._serialized_end=702
  _globals['_REGISTRYSERVICE']._serialized_start=902
  _globals['_REGISTRYSERVICE']._serialized_end=1204
# @@protoc_insertion_point(module_scope)
