# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from device import laser_navigation_pb2 as device_dot_laser__navigation__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in device/laser_navigation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LaserNavigationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPosition = channel.unary_unary(
                '/physical.device.LaserNavigationService/GetPosition',
                request_serializer=device_dot_laser__navigation__pb2.PositionRequest.SerializeToString,
                response_deserializer=device_dot_laser__navigation__pb2.PositionResponse.FromString,
                _registered_method=True)
        self.SetTarget = channel.unary_unary(
                '/physical.device.LaserNavigationService/SetTarget',
                request_serializer=device_dot_laser__navigation__pb2.SetTargetRequest.SerializeToString,
                response_deserializer=device_dot_laser__navigation__pb2.SetTargetResponse.FromString,
                _registered_method=True)
        self.CancelTarget = channel.unary_unary(
                '/physical.device.LaserNavigationService/CancelTarget',
                request_serializer=device_dot_laser__navigation__pb2.CancelTargetRequest.SerializeToString,
                response_deserializer=device_dot_laser__navigation__pb2.CancelTargetResponse.FromString,
                _registered_method=True)
        self.StartMapping = channel.unary_unary(
                '/physical.device.LaserNavigationService/StartMapping',
                request_serializer=device_dot_laser__navigation__pb2.StartMappingRequest.SerializeToString,
                response_deserializer=device_dot_laser__navigation__pb2.StartMappingResponse.FromString,
                _registered_method=True)
        self.StopMapping = channel.unary_unary(
                '/physical.device.LaserNavigationService/StopMapping',
                request_serializer=device_dot_laser__navigation__pb2.StopMappingRequest.SerializeToString,
                response_deserializer=device_dot_laser__navigation__pb2.StopMappingResponse.FromString,
                _registered_method=True)
        self.GetMap = channel.unary_unary(
                '/physical.device.LaserNavigationService/GetMap',
                request_serializer=device_dot_laser__navigation__pb2.GetMapRequest.SerializeToString,
                response_deserializer=device_dot_laser__navigation__pb2.GetMapResponse.FromString,
                _registered_method=True)
        self.SelectMap = channel.unary_unary(
                '/physical.device.LaserNavigationService/SelectMap',
                request_serializer=device_dot_laser__navigation__pb2.SelectMapRequest.SerializeToString,
                response_deserializer=device_dot_laser__navigation__pb2.SelectMapResponse.FromString,
                _registered_method=True)
        self.ListMaps = channel.unary_unary(
                '/physical.device.LaserNavigationService/ListMaps',
                request_serializer=device_dot_laser__navigation__pb2.ListMapsRequest.SerializeToString,
                response_deserializer=device_dot_laser__navigation__pb2.ListMapsResponse.FromString,
                _registered_method=True)
        self.ListMapPresets = channel.unary_unary(
                '/physical.device.LaserNavigationService/ListMapPresets',
                request_serializer=device_dot_laser__navigation__pb2.ListMapPresetsRequest.SerializeToString,
                response_deserializer=device_dot_laser__navigation__pb2.ListMapPresetsResponse.FromString,
                _registered_method=True)
        self.GetScanData = channel.unary_unary(
                '/physical.device.LaserNavigationService/GetScanData',
                request_serializer=device_dot_laser__navigation__pb2.ScanDataRequest.SerializeToString,
                response_deserializer=device_dot_laser__navigation__pb2.ScanDataResponse.FromString,
                _registered_method=True)
        self.GetPath = channel.unary_unary(
                '/physical.device.LaserNavigationService/GetPath',
                request_serializer=device_dot_laser__navigation__pb2.GetPathRequest.SerializeToString,
                response_deserializer=device_dot_laser__navigation__pb2.GetPathResponse.FromString,
                _registered_method=True)
        self.WatchNavigationStatus = channel.unary_stream(
                '/physical.device.LaserNavigationService/WatchNavigationStatus',
                request_serializer=device_dot_laser__navigation__pb2.WatchNavigationStatusRequest.SerializeToString,
                response_deserializer=device_dot_laser__navigation__pb2.NavigationStatus.FromString,
                _registered_method=True)


class LaserNavigationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPosition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTarget(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelTarget(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartMapping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopMapping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SelectMap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMaps(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMapPresets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScanData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchNavigationStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LaserNavigationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPosition,
                    request_deserializer=device_dot_laser__navigation__pb2.PositionRequest.FromString,
                    response_serializer=device_dot_laser__navigation__pb2.PositionResponse.SerializeToString,
            ),
            'SetTarget': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTarget,
                    request_deserializer=device_dot_laser__navigation__pb2.SetTargetRequest.FromString,
                    response_serializer=device_dot_laser__navigation__pb2.SetTargetResponse.SerializeToString,
            ),
            'CancelTarget': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelTarget,
                    request_deserializer=device_dot_laser__navigation__pb2.CancelTargetRequest.FromString,
                    response_serializer=device_dot_laser__navigation__pb2.CancelTargetResponse.SerializeToString,
            ),
            'StartMapping': grpc.unary_unary_rpc_method_handler(
                    servicer.StartMapping,
                    request_deserializer=device_dot_laser__navigation__pb2.StartMappingRequest.FromString,
                    response_serializer=device_dot_laser__navigation__pb2.StartMappingResponse.SerializeToString,
            ),
            'StopMapping': grpc.unary_unary_rpc_method_handler(
                    servicer.StopMapping,
                    request_deserializer=device_dot_laser__navigation__pb2.StopMappingRequest.FromString,
                    response_serializer=device_dot_laser__navigation__pb2.StopMappingResponse.SerializeToString,
            ),
            'GetMap': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMap,
                    request_deserializer=device_dot_laser__navigation__pb2.GetMapRequest.FromString,
                    response_serializer=device_dot_laser__navigation__pb2.GetMapResponse.SerializeToString,
            ),
            'SelectMap': grpc.unary_unary_rpc_method_handler(
                    servicer.SelectMap,
                    request_deserializer=device_dot_laser__navigation__pb2.SelectMapRequest.FromString,
                    response_serializer=device_dot_laser__navigation__pb2.SelectMapResponse.SerializeToString,
            ),
            'ListMaps': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMaps,
                    request_deserializer=device_dot_laser__navigation__pb2.ListMapsRequest.FromString,
                    response_serializer=device_dot_laser__navigation__pb2.ListMapsResponse.SerializeToString,
            ),
            'ListMapPresets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMapPresets,
                    request_deserializer=device_dot_laser__navigation__pb2.ListMapPresetsRequest.FromString,
                    response_serializer=device_dot_laser__navigation__pb2.ListMapPresetsResponse.SerializeToString,
            ),
            'GetScanData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScanData,
                    request_deserializer=device_dot_laser__navigation__pb2.ScanDataRequest.FromString,
                    response_serializer=device_dot_laser__navigation__pb2.ScanDataResponse.SerializeToString,
            ),
            'GetPath': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPath,
                    request_deserializer=device_dot_laser__navigation__pb2.GetPathRequest.FromString,
                    response_serializer=device_dot_laser__navigation__pb2.GetPathResponse.SerializeToString,
            ),
            'WatchNavigationStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchNavigationStatus,
                    request_deserializer=device_dot_laser__navigation__pb2.WatchNavigationStatusRequest.FromString,
                    response_serializer=device_dot_laser__navigation__pb2.NavigationStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'physical.device.LaserNavigationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('physical.device.LaserNavigationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LaserNavigationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.device.LaserNavigationService/GetPosition',
            device_dot_laser__navigation__pb2.PositionRequest.SerializeToString,
            device_dot_laser__navigation__pb2.PositionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetTarget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.device.LaserNavigationService/SetTarget',
            device_dot_laser__navigation__pb2.SetTargetRequest.SerializeToString,
            device_dot_laser__navigation__pb2.SetTargetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelTarget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.device.LaserNavigationService/CancelTarget',
            device_dot_laser__navigation__pb2.CancelTargetRequest.SerializeToString,
            device_dot_laser__navigation__pb2.CancelTargetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartMapping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.device.LaserNavigationService/StartMapping',
            device_dot_laser__navigation__pb2.StartMappingRequest.SerializeToString,
            device_dot_laser__navigation__pb2.StartMappingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopMapping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.device.LaserNavigationService/StopMapping',
            device_dot_laser__navigation__pb2.StopMappingRequest.SerializeToString,
            device_dot_laser__navigation__pb2.StopMappingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.device.LaserNavigationService/GetMap',
            device_dot_laser__navigation__pb2.GetMapRequest.SerializeToString,
            device_dot_laser__navigation__pb2.GetMapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SelectMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.device.LaserNavigationService/SelectMap',
            device_dot_laser__navigation__pb2.SelectMapRequest.SerializeToString,
            device_dot_laser__navigation__pb2.SelectMapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMaps(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.device.LaserNavigationService/ListMaps',
            device_dot_laser__navigation__pb2.ListMapsRequest.SerializeToString,
            device_dot_laser__navigation__pb2.ListMapsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMapPresets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.device.LaserNavigationService/ListMapPresets',
            device_dot_laser__navigation__pb2.ListMapPresetsRequest.SerializeToString,
            device_dot_laser__navigation__pb2.ListMapPresetsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScanData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.device.LaserNavigationService/GetScanData',
            device_dot_laser__navigation__pb2.ScanDataRequest.SerializeToString,
            device_dot_laser__navigation__pb2.ScanDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.device.LaserNavigationService/GetPath',
            device_dot_laser__navigation__pb2.GetPathRequest.SerializeToString,
            device_dot_laser__navigation__pb2.GetPathResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchNavigationStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/physical.device.LaserNavigationService/WatchNavigationStatus',
            device_dot_laser__navigation__pb2.WatchNavigationStatusRequest.SerializeToString,
            device_dot_laser__navigation__pb2.NavigationStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
