# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from device import robot_dog_pb2 as device_dot_robot__dog__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in device/robot_dog_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RobotDogServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Move = channel.unary_unary(
                '/physical.device.RobotDogService/Move',
                request_serializer=device_dot_robot__dog__pb2.MoveRequest.SerializeToString,
                response_deserializer=device_dot_robot__dog__pb2.MoveResponse.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/physical.device.RobotDogService/Stop',
                request_serializer=device_dot_robot__dog__pb2.StopRequest.SerializeToString,
                response_deserializer=device_dot_robot__dog__pb2.StopResponse.FromString,
                _registered_method=True)
        self.GetBattery = channel.unary_unary(
                '/physical.device.RobotDogService/GetBattery',
                request_serializer=device_dot_robot__dog__pb2.BatteryRequest.SerializeToString,
                response_deserializer=device_dot_robot__dog__pb2.BatteryResponse.FromString,
                _registered_method=True)
        self.SetPosture = channel.unary_unary(
                '/physical.device.RobotDogService/SetPosture',
                request_serializer=device_dot_robot__dog__pb2.PostureRequest.SerializeToString,
                response_deserializer=device_dot_robot__dog__pb2.PostureResponse.FromString,
                _registered_method=True)
        self.GetPose = channel.unary_unary(
                '/physical.device.RobotDogService/GetPose',
                request_serializer=device_dot_robot__dog__pb2.PoseRequest.SerializeToString,
                response_deserializer=device_dot_robot__dog__pb2.PoseResponse.FromString,
                _registered_method=True)
        self.Walk = channel.unary_unary(
                '/physical.device.RobotDogService/Walk',
                request_serializer=device_dot_robot__dog__pb2.WalkRequest.SerializeToString,
                response_deserializer=device_dot_robot__dog__pb2.WalkResponse.FromString,
                _registered_method=True)
        self.GetSensors = channel.unary_unary(
                '/physical.device.RobotDogService/GetSensors',
                request_serializer=device_dot_robot__dog__pb2.SensorsRequest.SerializeToString,
                response_deserializer=device_dot_robot__dog__pb2.SensorsResponse.FromString,
                _registered_method=True)
        self.SetMode = channel.unary_unary(
                '/physical.device.RobotDogService/SetMode',
                request_serializer=device_dot_robot__dog__pb2.SetModeRequest.SerializeToString,
                response_deserializer=device_dot_robot__dog__pb2.SetModeResponse.FromString,
                _registered_method=True)
        self.GetMode = channel.unary_unary(
                '/physical.device.RobotDogService/GetMode',
                request_serializer=device_dot_robot__dog__pb2.GetModeRequest.SerializeToString,
                response_deserializer=device_dot_robot__dog__pb2.GetModeResponse.FromString,
                _registered_method=True)
        self.WatchRobotDogStatus = channel.unary_stream(
                '/physical.device.RobotDogService/WatchRobotDogStatus',
                request_serializer=device_dot_robot__dog__pb2.WatchRobotDogStatusRequest.SerializeToString,
                response_deserializer=device_dot_robot__dog__pb2.RobotDogStatus.FromString,
                _registered_method=True)
        self.BalanceStand = channel.unary_unary(
                '/physical.device.RobotDogService/BalanceStand',
                request_serializer=device_dot_robot__dog__pb2.BalanceStandRequest.SerializeToString,
                response_deserializer=device_dot_robot__dog__pb2.BalanceStandResponse.FromString,
                _registered_method=True)
        self.StandUp = channel.unary_unary(
                '/physical.device.RobotDogService/StandUp',
                request_serializer=device_dot_robot__dog__pb2.StandUpRequest.SerializeToString,
                response_deserializer=device_dot_robot__dog__pb2.StandUpResponse.FromString,
                _registered_method=True)
        self.StandDown = channel.unary_unary(
                '/physical.device.RobotDogService/StandDown',
                request_serializer=device_dot_robot__dog__pb2.StandDownRequest.SerializeToString,
                response_deserializer=device_dot_robot__dog__pb2.StandDownResponse.FromString,
                _registered_method=True)
        self.RecoveryStand = channel.unary_unary(
                '/physical.device.RobotDogService/RecoveryStand',
                request_serializer=device_dot_robot__dog__pb2.RecoveryStandRequest.SerializeToString,
                response_deserializer=device_dot_robot__dog__pb2.RecoveryStandResponse.FromString,
                _registered_method=True)
        self.Damp = channel.unary_unary(
                '/physical.device.RobotDogService/Damp',
                request_serializer=device_dot_robot__dog__pb2.DampRequest.SerializeToString,
                response_deserializer=device_dot_robot__dog__pb2.DampResponse.FromString,
                _registered_method=True)
        self.SetAutoRecovery = channel.unary_unary(
                '/physical.device.RobotDogService/SetAutoRecovery',
                request_serializer=device_dot_robot__dog__pb2.SetAutoRecoveryRequest.SerializeToString,
                response_deserializer=device_dot_robot__dog__pb2.SetAutoRecoveryResponse.FromString,
                _registered_method=True)
        self.SwitchGait = channel.unary_unary(
                '/physical.device.RobotDogService/SwitchGait',
                request_serializer=device_dot_robot__dog__pb2.SwitchGaitRequest.SerializeToString,
                response_deserializer=device_dot_robot__dog__pb2.SwitchGaitResponse.FromString,
                _registered_method=True)
        self.SetSpeedLevel = channel.unary_unary(
                '/physical.device.RobotDogService/SetSpeedLevel',
                request_serializer=device_dot_robot__dog__pb2.SetSpeedLevelRequest.SerializeToString,
                response_deserializer=device_dot_robot__dog__pb2.SetSpeedLevelResponse.FromString,
                _registered_method=True)
        self.SetBodyHeight = channel.unary_unary(
                '/physical.device.RobotDogService/SetBodyHeight',
                request_serializer=device_dot_robot__dog__pb2.SetBodyHeightRequest.SerializeToString,
                response_deserializer=device_dot_robot__dog__pb2.SetBodyHeightResponse.FromString,
                _registered_method=True)
        self.GetControlState = channel.unary_unary(
                '/physical.device.RobotDogService/GetControlState',
                request_serializer=device_dot_robot__dog__pb2.GetControlStateRequest.SerializeToString,
                response_deserializer=device_dot_robot__dog__pb2.GetControlStateResponse.FromString,
                _registered_method=True)
        self.AuthorizeMotion = channel.unary_unary(
                '/physical.device.RobotDogService/AuthorizeMotion',
                request_serializer=device_dot_robot__dog__pb2.AuthorizeMotionRequest.SerializeToString,
                response_deserializer=device_dot_robot__dog__pb2.AuthorizeMotionResponse.FromString,
                _registered_method=True)
        self.ReleaseMotionAuthorization = channel.unary_unary(
                '/physical.device.RobotDogService/ReleaseMotionAuthorization',
                request_serializer=device_dot_robot__dog__pb2.ReleaseMotionAuthorizationRequest.SerializeToString,
                response_deserializer=device_dot_robot__dog__pb2.ReleaseMotionAuthorizationResponse.FromString,
                _registered_method=True)
        self.GetMotionAuthorization = channel.unary_unary(
                '/physical.device.RobotDogService/GetMotionAuthorization',
                request_serializer=device_dot_robot__dog__pb2.GetMotionAuthorizationRequest.SerializeToString,
                response_deserializer=device_dot_robot__dog__pb2.GetMotionAuthorizationResponse.FromString,
                _registered_method=True)


class RobotDogServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Move(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBattery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPosture(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Walk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSensors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchRobotDogStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BalanceStand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StandUp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StandDown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecoveryStand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Damp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAutoRecovery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SwitchGait(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSpeedLevel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetBodyHeight(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetControlState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AuthorizeMotion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseMotionAuthorization(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMotionAuthorization(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotDogServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Move': grpc.unary_unary_rpc_method_handler(
                    servicer.Move,
                    request_deserializer=device_dot_robot__dog__pb2.MoveRequest.FromString,
                    response_serializer=device_dot_robot__dog__pb2.MoveResponse.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=device_dot_robot__dog__pb2.StopRequest.FromString,
                    response_serializer=device_dot_robot__dog__pb2.StopResponse.SerializeToString,
            ),
            'GetBattery': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBattery,
                    request_deserializer=device_dot_robot__dog__pb2.BatteryRequest.FromString,
                    response_serializer=device_dot_robot__dog__pb2.BatteryResponse.SerializeToString,
            ),
            'SetPosture': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPosture,
                    request_deserializer=device_dot_robot__dog__pb2.PostureRequest.FromString,
                    response_serializer=device_dot_robot__dog__pb2.PostureResponse.SerializeToString,
            ),
            'GetPose': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPose,
                    request_deserializer=device_dot_robot__dog__pb2.PoseRequest.FromString,
                    response_serializer=device_dot_robot__dog__pb2.PoseResponse.SerializeToString,
            ),
            'Walk': grpc.unary_unary_rpc_method_handler(
                    servicer.Walk,
                    request_deserializer=device_dot_robot__dog__pb2.WalkRequest.FromString,
                    response_serializer=device_dot_robot__dog__pb2.WalkResponse.SerializeToString,
            ),
            'GetSensors': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSensors,
                    request_deserializer=device_dot_robot__dog__pb2.SensorsRequest.FromString,
                    response_serializer=device_dot_robot__dog__pb2.SensorsResponse.SerializeToString,
            ),
            'SetMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMode,
                    request_deserializer=device_dot_robot__dog__pb2.SetModeRequest.FromString,
                    response_serializer=device_dot_robot__dog__pb2.SetModeResponse.SerializeToString,
            ),
            'GetMode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMode,
                    request_deserializer=device_dot_robot__dog__pb2.GetModeRequest.FromString,
                    response_serializer=device_dot_robot__dog__pb2.GetModeResponse.SerializeToString,
            ),
            'WatchRobotDogStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchRobotDogStatus,
                    request_deserializer=device_dot_robot__dog__pb2.WatchRobotDogStatusRequest.FromString,
                    response_serializer=device_dot_robot__dog__pb2.RobotDogStatus.SerializeToString,
            ),
            'BalanceStand': grpc.unary_unary_rpc_method_handler(
                    servicer.BalanceStand,
                    request_deserializer=device_dot_robot__dog__pb2.BalanceStandRequest.FromString,
                    response_serializer=device_dot_robot__dog__pb2.BalanceStandResponse.SerializeToString,
            ),
            'StandUp': grpc.unary_unary_rpc_method_handler(
                    servicer.StandUp,
                    request_deserializer=device_dot_robot__dog__pb2.StandUpRequest.FromString,
                    response_serializer=device_dot_robot__dog__pb2.StandUpResponse.SerializeToString,
            ),
            'StandDown': grpc.unary_unary_rpc_method_handler(
                    servicer.StandDown,
                    request_deserializer=device_dot_robot__dog__pb2.StandDownRequest.FromString,
                    response_serializer=device_dot_robot__dog__pb2.StandDownResponse.SerializeToString,
            ),
            'RecoveryStand': grpc.unary_unary_rpc_method_handler(
                    servicer.RecoveryStand,
                    request_deserializer=device_dot_robot__dog__pb2.RecoveryStandRequest.FromString,
                    response_serializer=device_dot_robot__dog__pb2.RecoveryStandResponse.SerializeToString,
            ),
            'Damp': grpc.unary_unary_rpc_method_handler(
                    servicer.Damp,
                    request_deserializer=device_dot_robot__dog__pb2.DampRequest.FromString,
                    response_serializer=device_dot_robot__dog__pb2.DampResponse.SerializeToString,
            ),
            'SetAutoRecovery': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAutoRecovery,
                    request_deserializer=device_dot_robot__dog__pb2.SetAutoRecoveryRequest.FromString,
                    response_serializer=device_dot_robot__dog__pb2.SetAutoRecoveryResponse.SerializeToString,
            ),
            'SwitchGait': grpc.unary_unary_rpc_method_handler(
                    servicer.SwitchGait,
                    request_deserializer=device_dot_robot__dog__pb2.SwitchGaitRequest.FromString,
                    response_serializer=device_dot_robot__dog__pb2.SwitchGaitResponse.SerializeToString,
            ),
            'SetSpeedLevel': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSpeedLevel,
                    request_deserializer=device_dot_robot__dog__pb2.SetSpeedLevelRequest.FromString,
                    response_serializer=device_dot_robot__dog__pb2.SetSpeedLevelResponse.SerializeToString,
            ),
            'SetBodyHeight': grpc.unary_unary_rpc_method_handler(
                    servicer.SetBodyHeight,
                    request_deserializer=device_dot_robot__dog__pb2.SetBodyHeightRequest.FromString,
                    response_serializer=device_dot_robot__dog__pb2.SetBodyHeightResponse.SerializeToString,
            ),
            'GetControlState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetControlState,
                    request_deserializer=device_dot_robot__dog__pb2.GetControlStateRequest.FromString,
                    response_serializer=device_dot_robot__dog__pb2.GetControlStateResponse.SerializeToString,
            ),
            'AuthorizeMotion': grpc.unary_unary_rpc_method_handler(
                    servicer.AuthorizeMotion,
                    request_deserializer=device_dot_robot__dog__pb2.AuthorizeMotionRequest.FromString,
                    response_serializer=device_dot_robot__dog__pb2.AuthorizeMotionResponse.SerializeToString,
            ),
            'ReleaseMotionAuthorization': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseMotionAuthorization,
                    request_deserializer=device_dot_robot__dog__pb2.ReleaseMotionAuthorizationRequest.FromString,
                    response_serializer=device_dot_robot__dog__pb2.ReleaseMotionAuthorizationResponse.SerializeToString,
            ),
            'GetMotionAuthorization': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMotionAuthorization,
                    request_deserializer=device_dot_robot__dog__pb2.GetMotionAuthorizationRequest.FromString,
                    response_serializer=device_dot_robot__dog__pb2.GetMotionAuthorizationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'physical.device.RobotDogService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('physical.device.RobotDogService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RobotDogService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Move(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.device.RobotDogService/Move',
            device_dot_robot__dog__pb2.MoveRequest.SerializeToString,
            device_dot_robot__dog__pb2.MoveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.device.RobotDogService/Stop',
            device_dot_robot__dog__pb2.StopRequest.SerializeToString,
            device_dot_robot__dog__pb2.StopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBattery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.device.RobotDogService/GetBattery',
            device_dot_robot__dog__pb2.BatteryRequest.SerializeToString,
            device_dot_robot__dog__pb2.BatteryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPosture(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.device.RobotDogService/SetPosture',
            device_dot_robot__dog__pb2.PostureRequest.SerializeToString,
            device_dot_robot__dog__pb2.PostureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.device.RobotDogService/GetPose',
            device_dot_robot__dog__pb2.PoseRequest.SerializeToString,
            device_dot_robot__dog__pb2.PoseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Walk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.device.RobotDogService/Walk',
            device_dot_robot__dog__pb2.WalkRequest.SerializeToString,
            device_dot_robot__dog__pb2.WalkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSensors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.device.RobotDogService/GetSensors',
            device_dot_robot__dog__pb2.SensorsRequest.SerializeToString,
            device_dot_robot__dog__pb2.SensorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.device.RobotDogService/SetMode',
            device_dot_robot__dog__pb2.SetModeRequest.SerializeToString,
            device_dot_robot__dog__pb2.SetModeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.device.RobotDogService/GetMode',
            device_dot_robot__dog__pb2.GetModeRequest.SerializeToString,
            device_dot_robot__dog__pb2.GetModeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchRobotDogStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/physical.device.RobotDogService/WatchRobotDogStatus',
            device_dot_robot__dog__pb2.WatchRobotDogStatusRequest.SerializeToString,
            device_dot_robot__dog__pb2.RobotDogStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BalanceStand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.device.RobotDogService/BalanceStand',
            device_dot_robot__dog__pb2.BalanceStandRequest.SerializeToString,
            device_dot_robot__dog__pb2.BalanceStandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StandUp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.device.RobotDogService/StandUp',
            device_dot_robot__dog__pb2.StandUpRequest.SerializeToString,
            device_dot_robot__dog__pb2.StandUpResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StandDown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.device.RobotDogService/StandDown',
            device_dot_robot__dog__pb2.StandDownRequest.SerializeToString,
            device_dot_robot__dog__pb2.StandDownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecoveryStand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.device.RobotDogService/RecoveryStand',
            device_dot_robot__dog__pb2.RecoveryStandRequest.SerializeToString,
            device_dot_robot__dog__pb2.RecoveryStandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Damp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.device.RobotDogService/Damp',
            device_dot_robot__dog__pb2.DampRequest.SerializeToString,
            device_dot_robot__dog__pb2.DampResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetAutoRecovery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.device.RobotDogService/SetAutoRecovery',
            device_dot_robot__dog__pb2.SetAutoRecoveryRequest.SerializeToString,
            device_dot_robot__dog__pb2.SetAutoRecoveryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SwitchGait(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.device.RobotDogService/SwitchGait',
            device_dot_robot__dog__pb2.SwitchGaitRequest.SerializeToString,
            device_dot_robot__dog__pb2.SwitchGaitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSpeedLevel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.device.RobotDogService/SetSpeedLevel',
            device_dot_robot__dog__pb2.SetSpeedLevelRequest.SerializeToString,
            device_dot_robot__dog__pb2.SetSpeedLevelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetBodyHeight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.device.RobotDogService/SetBodyHeight',
            device_dot_robot__dog__pb2.SetBodyHeightRequest.SerializeToString,
            device_dot_robot__dog__pb2.SetBodyHeightResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetControlState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.device.RobotDogService/GetControlState',
            device_dot_robot__dog__pb2.GetControlStateRequest.SerializeToString,
            device_dot_robot__dog__pb2.GetControlStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AuthorizeMotion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.device.RobotDogService/AuthorizeMotion',
            device_dot_robot__dog__pb2.AuthorizeMotionRequest.SerializeToString,
            device_dot_robot__dog__pb2.AuthorizeMotionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseMotionAuthorization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.device.RobotDogService/ReleaseMotionAuthorization',
            device_dot_robot__dog__pb2.ReleaseMotionAuthorizationRequest.SerializeToString,
            device_dot_robot__dog__pb2.ReleaseMotionAuthorizationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMotionAuthorization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.device.RobotDogService/GetMotionAuthorization',
            device_dot_robot__dog__pb2.GetMotionAuthorizationRequest.SerializeToString,
            device_dot_robot__dog__pb2.GetMotionAuthorizationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
