# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from device import robot_dog_pb2 as device_dot_robot__dog__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in device/robot_dog_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RobotDogServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Move = channel.unary_unary(
                '/physical.device.RobotDogService/Move',
                request_serializer=device_dot_robot__dog__pb2.MoveRequest.SerializeToString,
                response_deserializer=device_dot_robot__dog__pb2.MoveResponse.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/physical.device.RobotDogService/Stop',
                request_serializer=device_dot_robot__dog__pb2.StopRequest.SerializeToString,
                response_deserializer=device_dot_robot__dog__pb2.StopResponse.FromString,
                _registered_method=True)
        self.GetBattery = channel.unary_unary(
                '/physical.device.RobotDogService/GetBattery',
                request_serializer=device_dot_robot__dog__pb2.BatteryRequest.SerializeToString,
                response_deserializer=device_dot_robot__dog__pb2.BatteryResponse.FromString,
                _registered_method=True)
        self.SetPosture = channel.unary_unary(
                '/physical.device.RobotDogService/SetPosture',
                request_serializer=device_dot_robot__dog__pb2.PostureRequest.SerializeToString,
                response_deserializer=device_dot_robot__dog__pb2.PostureResponse.FromString,
                _registered_method=True)
        self.GetPose = channel.unary_unary(
                '/physical.device.RobotDogService/GetPose',
                request_serializer=device_dot_robot__dog__pb2.PoseRequest.SerializeToString,
                response_deserializer=device_dot_robot__dog__pb2.PoseResponse.FromString,
                _registered_method=True)
        self.Walk = channel.unary_unary(
                '/physical.device.RobotDogService/Walk',
                request_serializer=device_dot_robot__dog__pb2.WalkRequest.SerializeToString,
                response_deserializer=device_dot_robot__dog__pb2.WalkResponse.FromString,
                _registered_method=True)
        self.GetSensors = channel.unary_unary(
                '/physical.device.RobotDogService/GetSensors',
                request_serializer=device_dot_robot__dog__pb2.SensorsRequest.SerializeToString,
                response_deserializer=device_dot_robot__dog__pb2.SensorsResponse.FromString,
                _registered_method=True)
        self.SetMode = channel.unary_unary(
                '/physical.device.RobotDogService/SetMode',
                request_serializer=device_dot_robot__dog__pb2.SetModeRequest.SerializeToString,
                response_deserializer=device_dot_robot__dog__pb2.SetModeResponse.FromString,
                _registered_method=True)
        self.GetMode = channel.unary_unary(
                '/physical.device.RobotDogService/GetMode',
                request_serializer=device_dot_robot__dog__pb2.GetModeRequest.SerializeToString,
                response_deserializer=device_dot_robot__dog__pb2.GetModeResponse.FromString,
                _registered_method=True)
        self.WatchRobotDogStatus = channel.unary_stream(
                '/physical.device.RobotDogService/WatchRobotDogStatus',
                request_serializer=device_dot_robot__dog__pb2.WatchRobotDogStatusRequest.SerializeToString,
                response_deserializer=device_dot_robot__dog__pb2.RobotDogStatus.FromString,
                _registered_method=True)


class RobotDogServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Move(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBattery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPosture(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Walk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSensors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchRobotDogStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotDogServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Move': grpc.unary_unary_rpc_method_handler(
                    servicer.Move,
                    request_deserializer=device_dot_robot__dog__pb2.MoveRequest.FromString,
                    response_serializer=device_dot_robot__dog__pb2.MoveResponse.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=device_dot_robot__dog__pb2.StopRequest.FromString,
                    response_serializer=device_dot_robot__dog__pb2.StopResponse.SerializeToString,
            ),
            'GetBattery': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBattery,
                    request_deserializer=device_dot_robot__dog__pb2.BatteryRequest.FromString,
                    response_serializer=device_dot_robot__dog__pb2.BatteryResponse.SerializeToString,
            ),
            'SetPosture': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPosture,
                    request_deserializer=device_dot_robot__dog__pb2.PostureRequest.FromString,
                    response_serializer=device_dot_robot__dog__pb2.PostureResponse.SerializeToString,
            ),
            'GetPose': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPose,
                    request_deserializer=device_dot_robot__dog__pb2.PoseRequest.FromString,
                    response_serializer=device_dot_robot__dog__pb2.PoseResponse.SerializeToString,
            ),
            'Walk': grpc.unary_unary_rpc_method_handler(
                    servicer.Walk,
                    request_deserializer=device_dot_robot__dog__pb2.WalkRequest.FromString,
                    response_serializer=device_dot_robot__dog__pb2.WalkResponse.SerializeToString,
            ),
            'GetSensors': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSensors,
                    request_deserializer=device_dot_robot__dog__pb2.SensorsRequest.FromString,
                    response_serializer=device_dot_robot__dog__pb2.SensorsResponse.SerializeToString,
            ),
            'SetMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMode,
                    request_deserializer=device_dot_robot__dog__pb2.SetModeRequest.FromString,
                    response_serializer=device_dot_robot__dog__pb2.SetModeResponse.SerializeToString,
            ),
            'GetMode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMode,
                    request_deserializer=device_dot_robot__dog__pb2.GetModeRequest.FromString,
                    response_serializer=device_dot_robot__dog__pb2.GetModeResponse.SerializeToString,
            ),
            'WatchRobotDogStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchRobotDogStatus,
                    request_deserializer=device_dot_robot__dog__pb2.WatchRobotDogStatusRequest.FromString,
                    response_serializer=device_dot_robot__dog__pb2.RobotDogStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'physical.device.RobotDogService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('physical.device.RobotDogService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RobotDogService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Move(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.device.RobotDogService/Move',
            device_dot_robot__dog__pb2.MoveRequest.SerializeToString,
            device_dot_robot__dog__pb2.MoveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.device.RobotDogService/Stop',
            device_dot_robot__dog__pb2.StopRequest.SerializeToString,
            device_dot_robot__dog__pb2.StopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBattery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.device.RobotDogService/GetBattery',
            device_dot_robot__dog__pb2.BatteryRequest.SerializeToString,
            device_dot_robot__dog__pb2.BatteryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPosture(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.device.RobotDogService/SetPosture',
            device_dot_robot__dog__pb2.PostureRequest.SerializeToString,
            device_dot_robot__dog__pb2.PostureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.device.RobotDogService/GetPose',
            device_dot_robot__dog__pb2.PoseRequest.SerializeToString,
            device_dot_robot__dog__pb2.PoseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Walk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.device.RobotDogService/Walk',
            device_dot_robot__dog__pb2.WalkRequest.SerializeToString,
            device_dot_robot__dog__pb2.WalkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSensors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.device.RobotDogService/GetSensors',
            device_dot_robot__dog__pb2.SensorsRequest.SerializeToString,
            device_dot_robot__dog__pb2.SensorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.device.RobotDogService/SetMode',
            device_dot_robot__dog__pb2.SetModeRequest.SerializeToString,
            device_dot_robot__dog__pb2.SetModeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physical.device.RobotDogService/GetMode',
            device_dot_robot__dog__pb2.GetModeRequest.SerializeToString,
            device_dot_robot__dog__pb2.GetModeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchRobotDogStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/physical.device.RobotDogService/WatchRobotDogStatus',
            device_dot_robot__dog__pb2.WatchRobotDogStatusRequest.SerializeToString,
            device_dot_robot__dog__pb2.RobotDogStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
